// =================================================================
//
// File: example04.cpp
// Author: Pedro Perez
// Description: This file implements the algorithm to find the 
//		minimum value in an array using C/C++ threads. To 
//		compile:
//		g++ -o app -pthread example04.cpp
//
// Copyright (c) 2024 by Tecnologico de Monterrey.
// All Rights Reserved. May be reproduced for any non-commercial
// purpose.
//
// =================================================================

#include <iostream>
#include <iomanip>
#include <chrono>
#include <thread>
#include <cmath>
#include <cstring>
#include "utils.h"

using namespace std;
using namespace std::chrono;

#define SIZE 	1000000000 // 1e9
#define THREADS std::thread::hardware_concurrency()

// =================================================================
// Calculates the minimum value of an array found within the 
// [start, end] segment. The obtained value is assigned to the 
// variable by reference 'result' .
//
// @param start, the lower limit.
// @param end, the upper limit.
// @param array, an array of integer numbers.
// @param result, to this variable is assigned the result of the 
//                operation.
// =================================================================
void minimum(int start, int end, int *array, int &result) {
    int local = array[start];
    for (int i = start + 1; i < end; i++) {
        if (array[i] < local) {
            local = array[i];
        }
    }
    result = local;
}

int main(int argc, char* argv[]) {
    // We will use pointers to handle large arrays.
    int *array, result;

    // These variables are used to keep track of the execution time.
    high_resolution_clock::time_point start, end;
    double timeElapsed;

    // We create the array.
    array = new int [SIZE];
    
    // We fill it with random numbers.
    random_array(array, SIZE);
    display_array("array:", array);

    // We calculate the block size that is assigned to each thread 
    // by dividing the task size by the number of threads.
    int blockSize = ceil((double) SIZE / THREADS);
    thread threads[THREADS];

    // We use the 'results' array to store the results generated by 
    // each thread.
    int results[THREADS];

    // We initialize each location in the array to zero.
    memset(results, 0, sizeof(int) * THREADS);
    
    // We execute the task at least 10 times (N). It is necessary 
    // to do so, since it allows us to reduce the impact of the 
    // load on the operating system at the time of execution.
    cout << "Starting...\n";
    timeElapsed = 0;
    for (int j = 0; j < N; j++) {
        // We take a clock record before execution.
        start = high_resolution_clock::now();

        // We generate the threads and assign them the tasks they 
        // must perform. Each task is delimited within the range 
        // [start, end). 
        // FORK STEP
        for (int i = 0; i < THREADS; i++) {
            int start = (i * blockSize);
            int end = (i != (THREADS - 1))? ((i + 1) * blockSize) : SIZE;
            threads[i] = thread(minimum, start, end, array, std::ref(results[i]));
        }

        // We wait for all the threads to finish their assigned 
        // task. After a particular thread has finished, we retrieve 
        // its partial result and use it to calculate the overall 
        // result.
        // JOIN STEP
        result = array[0];
        for (int i = 0; i < THREADS; i++) {
            threads[i].join();
            if (results[i] < result) {
                result = results[i];
            }
        }

        // We take a clock record after execution. We calculate the 
        // difference between the two records. This difference is 
        // the time it took to execute the task.
        end = high_resolution_clock::now();
        timeElapsed += 
            duration<double, std::milli>(end - start).count();
    }
    // We display the result and the average execution time.
    cout << "result = " << result << "\n";
    cout << "avg time = " << fixed << setprecision(3) 
         << (timeElapsed / N) <<  " ms\n";

    // We delete all the allocated memory.
    delete [] array;

    return 0;
}
